### ISSUE TITLE
Multiple amr/disarm state

### ISSUE THREAD

**Issue by DeltaFox0018** [johnnybegood/ha-ksenia-lares#15]
Hello,
in my configuration I have 2 types of alarm disarming since the same control unit controls 2 houses
I have the same case for arm night and arm away

Ex:
I have the following actions
disarm 1
total arm 1
night arm 1
disarm 2
total arm 2
night arm 2

Is there an option to create custom buttons where I go and say which action it should do of the ones indicated above?
Obviously the labels are different

**Comment by johnnybegood** [comment]
Hi @DeltaFox0018, do these exist as scenarios? I could expose all scenarios as scenes or via a custom service

**Comment by DeltaFox0018** [comment]
Hi @johnnybegood , those shown above are scenarios present on KSenia Lares.

These are all of my scenarios on KSenia
<img width="212" alt="image" src="https://github.com/johnnybegood/ha-ksenia-lares/assets/35847603/606ce8ad-3559-4956-9b4c-3403edd4b4f8">


<img width="586" alt="image" src="https://github.com/johnnybegood/ha-ksenia-lares/assets/35847603/af2c68bf-5178-4445-8a0d-33931ff4a663">


In the configuration for the night state I entered 1

I wanted to know if there was a possibility to add night 2 scenario to add another scenario.

**Comment by johnnybegood** [comment]
Home assistant only has 1 night armed status per panel. But I would be possible to expose all scenarios via a custom service, a scene entity or device action. Not sure which of these would be best

**Comment by DeltaFox0018** [comment]
Ok thanks, I will do some testing to find the best solution

Thank you
