### ISSUE TITLE
Doesn't start in HA 2022.7

### ISSUE THREAD

**Issue by johnnybegood** [johnnybegood/ha-ksenia-lares#2]
After 2022.7 update it doesn't work anymore...

_Originally posted by @Rui10 in https://github.com/johnnybegood/ha-ksenia-lares/issues/1#issuecomment-1179511025_

**Comment by Rui10** [comment]
Is there any possibility to have ha-ksenia-lares update?

**Comment by johnnybegood** [comment]
@Rui10 loading the last version via HACS should fix it
