### ISSUE TITLE
Switch to bypass zones

### ISSUE THREAD

**Issue by IAmVespa** [johnnybegood/ha-ksenia-lares#20]
**Is your feature request related to a problem? Please describe.**
Sometimes is handy to bypass certain zones in order to fully arm the system (eg, slightly open window in summer).

**Describe the solution you'd like**
Create a switch for each zone in order to toggle the zone bypass function.

**Describe alternatives you've considered**
Used to be very simple with old BTicino MyHomeUp app, just a couple of touch away. With the new Home + Control is way too complex (hidden many touches away).

**Device**
BTicino 4200 ( Kesnia Lares 16IP)

**Additional context**
Info on current status (bypass - `BYPASS` or `UN_BYPASS`) easily read from the `/zonesStatus16IP.xml`
Command which need to be used to toggle the switch: `http://192.168.XXX.YYY/xml/cmd/cmdOk.xml?cmd=setByPassZone&pin=XXXXXX&zoneId=2&zoneValue=0`
Where:
- _pin_: user code (maybe needs to be hardcoded from configuration ??)
- _zoneId_: zone number as ordered in `/zonesDescription16IP.xml` starting from 1
- _zoneValue_:
&nbsp;&nbsp;&nbsp;- 1: bypass ON
&nbsp;&nbsp;&nbsp;- 0: bypass OFF

Let me know if more info are needed

**Comment by johnnybegood** [comment]
I am a bit hesitant to store a PIN, maybe I should expose this a service instead.

**Comment by johnnybegood** [comment]
In alarm control panel logic there is something available called AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS, but not sure yet how the bypass works here

**Comment by IAmVespa** [comment]
I understand your point, storing the PIN is far from ideal.
I am not familiar with the concept of services, but, if it gives the ability to bypass/unbypass a zone, than only a simple binary sensor is needed to know the current zone status.

I took a look at the ARM_CUSTOM_BYPASS option in the Alarm Panel, but, from my understanding, is currently only a further alarm activation option. Do you see any other option with the ARM_CUSTOM_BYPASS?

**Comment by johnnybegood** [comment]
It could be combined with the switch, but only at arm custom bypass the bypass is done. Then I have the PIN from user entry

**Comment by IAmVespa** [comment]
Yeah, that could work. 
Then, would you bring it back to unbypass condition each time the alarm is disarmed?

**Comment by johnnybegood** [comment]
@IAmVespa I went with the PIN storage approach, other integration also seem to use this

**Comment by johnnybegood** [comment]
Available as beta version

**Comment by IAmVespa** [comment]
Thanks a lot, just installed!
So far, works like a charm.
