### ISSUE TITLE
Ksenia Gateway HTTP

### ISSUE THREAD

**Issue by curgio** [johnnybegood/ha-ksenia-lares#31]
Hi,
please could you confirm if it's necessary the Gateway HTTP of Ksenia for this integration?
Thanks a lot in advance!
Giovanni

**Comment by johnnybegood** [comment]
The integration works with pre 4.0 version with a direct connection. If you conenct to http://LOCAL-IP:port, you should get a browser window (not a webpage) with a login. If so, this integration is compatible
