### ISSUE TITLE
Integration stops working after upgrade HA to 2024.12.0

### ISSUE THREAD

**Issue by One35SEven** [johnnybegood/ha-ksenia-lares#34]
The integration stops working after upgrading to Home Assistant to 2024.12.0.
Suspect that upgrade of Python in this release is the cause.

Logs:

Logger: homeassistant.setup
Bron: setup.py:269
Eerst voorgekomen: 10:22:02 (1 gebeurtenissen)
Laatst gelogd: 10:22:02

Setup failed for custom integration 'ksenia_lares': Requirements for ksenia_lares not found: ['lxml==4.9.4'].

Logger: homeassistant.util.package
Bron: util/package.py:152
Eerst voorgekomen: 10:22:02 (3 gebeurtenissen)
Laatst gelogd: 10:22:02

Unable to install package lxml==4.9.4: × No solution found when resolving dependencies: ╰─▶ Because lxml==4.9.4 has no wheels with a matching Python ABI tag and you require lxml==4.9.4, we can conclude that your requirements are unsatisfiable.

**Comment by johnnybegood** [comment]
Working on it via #32

**Comment by johnnybegood** [comment]
Fixed in 1.2.7
