### ISSUE TITLE
I'd love to contribute, where have you found the Ksenia pre 4.0 documentation? 

### ISSUE THREAD

**Issue by zelloxy** [johnnybegood/ha-ksenia-lares#9]
I've been looking everywhere for it.

**Comment by johnnybegood** [comment]
Unfortunately nowhere, I have been inspecting the API using browser tools with the web application of my KSenia at home

**Comment by zelloxy** [comment]
I have my Ksenia setup at home but I didn't even know of a web interface (was never told). What port is it accessable at?

**Comment by johnnybegood** [comment]
Default port is 4202, I learned from https://github.com/johnnybegood/ha-ksenia-lares/issues/1#issuecomment-1510365318 that this not standard available

**Comment by johnnybegood** [comment]
closing due to idle
